name: Build and release

on:
  - push
  - pull_request

permissions: write-all

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            asset_name: "Release/FIVE_IN_A_ROW.exe"
          - os: ubuntu-latest
            asset_name: "FIVE_IN_A_ROW"
          - os: macos-latest
            asset_name: "FIVE_IN_A_ROW"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.5.3"

      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.os }}
          path: bin/release/${{ matrix.asset_name }}

      - name: Create release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file: bin/release/${{ matrix.asset_name }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
