name: Build and release

on:
  - push
  - pull_request

permissions: write-all

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            os_name: windows
            asset_path: "Release/FIVE_IN_A_ROW.exe"
            file_extension: ".exe"
          - os: ubuntu-latest
            os_name: linux
            asset_path: "FIVE_IN_A_ROW"
            file_extension: ""
          - os: macos-latest
            os_name: macos
            asset_path: "FIVE_IN_A_ROW"
            file_extension: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.5.3"

      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.os }}
          path: bin/release/${{ matrix.asset_path }}

      - name: Create release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          asset_name: FIVE_IN_A_ROW-${{ matrix.os_name }}-$tag${{ matrix.file_extension }}
          file: bin/release/${{ matrix.asset_path }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
