name: Build and release

on:
  - push
  - pull_request

permissions: 
  contents: write

jobs:
  build-and-release:
    name: "Build and release (${{ matrix.os_name }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            os_name: windows
            asset_path: "FIVE_IN_A_ROW.exe"
            file_extension: ".exe"
          - os: ubuntu-latest
            os_name: linux
            asset_path: "FIVE_IN_A_ROW*.AppImage"
            file_extension: ".AppImage"
          - os: macos-latest
            os_name: macos
            asset_path: "FIVE_IN_A_ROW.dmg"
            file_extension: ".dmg"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.5.3"

      - name: Configure CMake
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Install FUSE
        if: matrix.os_name == 'linux'
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2

      - name: Install LinuxDeploy
        if: matrix.os_name == 'linux'
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage

      - name: Package (Linux)
        if: matrix.os_name == 'linux'
        run: linuxdeploy-x86_64.AppImage --plugin=qt --output=appimage --executable=bin/release/FIVE_IN_A_ROW --appdir AppDir

      - name: Package (macOS)
        if: matrix.os_name == 'macos'
        run: sudo macdeployqt FIVE_IN_A_ROW.app -verbose=1 -dmg

      - name: Package (Windows)
        if: matrix.os_name == 'windows'
        run: windeployqt.exe FIVE_IN_A_ROW.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.os_name }}
          path: ${{ matrix.asset_path }}

      - name: Create release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          asset_name: FIVE_IN_A_ROW-${{ matrix.os_name }}-$tag${{ matrix.file_extension }}
          file: ${{ matrix.asset_path }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
